// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CameraState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<void> initCams() => RustLib.instance.api.crateApiCameraInitCams();

Future<List<Cameras>> checkForCameras() =>
    RustLib.instance.api.crateApiCameraCheckForCameras();

Future<void> setMask({required bool mask}) =>
    RustLib.instance.api.crateApiCameraSetMask(mask: mask);

Future<void> setBackground({required List<int> background}) =>
    RustLib.instance.api.crateApiCameraSetBackground(background: background);

Future<void> setDebug({required bool debug}) =>
    RustLib.instance.api.crateApiCameraSetDebug(debug: debug);

Stream<Uint8List> streamCamera({required int id}) =>
    RustLib.instance.api.crateApiCameraStreamCamera(id: id);

class Cameras {
  final String id;
  final String name;

  const Cameras({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cameras &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
